config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :menus do
    resources :orders, only: [:index, :create, :update, :new]
  end
  resources :orders, only: [:destroy]

  get "chef/orders" => "orders#chef_index"

  get "orders" => "orders#index"
  get "chef/" => "pages#chef"

  get "landingchef/:id" => "pages#landingchef", as: "landingchef"
  get "orders/:id/approve" => "orders#approve", as: "approve"
  get "orders/:id/reject" => "orders#reject", as: "reject"
  get "mymenus" => "menus#mymenus"


  mount Attachinary::Engine => "/attachinary"

  resources :users, only: [:show, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
require 'date'
class Menu < ApplicationRecord
  belongs_to :user
  has_many :orders
  validates :name, :description, :price, :portions, :availability, presence: true
  validates_inclusion_of :category, :in => ["lunch", "dinner"], :allow_nil => false
  has_attachment :photo

  before_save :check_stock

  def ordered_quantity(jump=Order.new)
    orders.inject(0){|sum,x| sum + ((x.approved == false || x.id == jump.id ) ? 0 : x.portions) }
  end

  def check_stock
    qtt = self.ordered_quantity()
    if qtt > self.portions
      errors[:portions] <<  "#{qtt} portion#{qtt>1 ? 's' : ''} are already booked, you can not have less portions available"
      throw :abort
    end
  end

  def friendly_date
    self.availability.strftime("%e %B, %Y")
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    portions = params[:portions]
    price = params[:price]
    # category = params[:category]
    date = params[:date]

    @menus = Menu.all

    # @menus = @menus.where(category: category) if category
    # @menus = @menus.where(availability: date) if date
    @menus = @menus.where("portions >= ? ", portions) unless portions.blank?
    @menus = @menus.where("price <= ? ", price) unless price.blank?
    @menus = @menus.select { |menu| menu.user.city == params[:city] } if ( params[:city] && !params[:city].empty?)
    @total = @menus.count

  end

  def show
    @order = Order.new
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.user = current_user

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Your menu was successfully created. It looks delicious' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Your menu was successfully updated.It looks delicious' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Your menu was successfully destroyed. You did good, It was digusting :) LOL' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :description, :price, :portions, :availability, :photo, :category)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<div class="show">
  <div class="container">
    <div class="row">
      <div class="forms form-transparent col-sm-6 col-sm-offset-3 col-lg-6 col-lg-offset-3">
        <div class="section">
          <h2 class="text-center small">Publish a menu</h2>
        </div>

        <%= simple_form_for(@menu) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :starter %>
            <%= f.input :meal %>
            <%= f.input :dessert %>
            <%= f.input :price %>
            <%= f.input :portions %>
            <%= f.input :availability %>
            <%= f.input :category , priority: [ "dinner" ], collection: [ "lunch", "dinner"] %>
            <%= f.input :photo, as: :attachinary %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: 'btn cta-btn btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<div class="searchpage">
  <div class="hidden-xs col-sm-6 col-md-6 col-lg-6 left-side">

      <%= form_tag(menus_path, method: "get", class: "little-searchbar") do %>
        <%= text_field_tag :date, nil, placeholder: 'Date?', "data-provide" => "datepicker", class: 'small' %>

        <div class="styled-select">
        <%= select_tag :portions, options_for_select([1,2,3,4,6,8,10,12], :selected => params[:portions]), include_blank: 'Portions' %>
        </div>
        <div class="styled-select">
          <%= select_tag :price, options_for_select(([3,5,10,15,20,30,50,70,100,150,200].map { |prix| "#{prix} €" }).zip([3,5,10,15,20,30,50,70,100,150,200]), :selected => params[:price]), include_blank: 'Budget' %>
        </div>

        <%= submit_tag "Filter" %>
        <%
        city = ""
        city = "in #{params[:city]} !" if params[:city]
        %>
        <% total = "#{@total} results #{city}" %>
        <%= label_tag 'name', total, class: 'small_total' %>

      <% end %>

      <div class="row scroll">
        <% if @menus.count.zero? %>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 no-results text-center">
          <h2>Shoot. Nothing to show here!</h2>
          <div>Please try new filters.</div>
        </div>
        <% else
        @menus.each do |menu| %>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">

            <div class="menu-card">
              <% menu_photo = (menu.photo ? cl_image_path(menu.photo.path) : image_path("no_photo_menu.png")) %>
              <div class="photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= menu_photo %>');"><%= link_to " ", menu, class: 'link-menu' %>
              </div>

            <%= link_to landingchef_path(menu.user.id), class: 'link-chef' do %>
              <%= menu.user.photo ? cl_image_tag(menu.user.photo.path, width: 200, height: 200, crop: :fill, class: 'avatar') : image_tag("no_photo.png", width: 200, height: 200, crop: :fill, class: 'avatar') %>
            <% end %>

              <div class="description">
                <h3><%= menu.name %></h3>
                <p><%= truncate(menu.description, :length => 38) %></p>
                <span><%= menu.price %>€</span>
              </div>
              <div class="params">
                <div class="param"><i class="fa fa-calendar"></i> <%= menu.friendly_date %></div>
                <div class="param"><i class="fa fa-cutlery"></i> <%= menu.portions %></div>
              </div>
              <div class="localisation">
                <p><i class="fa fa-map-marker"></i> <%= menu.user.city if menu.user.city != NIL %></p>
                <%= link_to "Order now", menu, class: 'btn cta-btn' %>
              </div>
            </div>

          </div>
        <% end end %>
      </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 map">

  <div id="map" style="width: 100%; height: 100%;"></div>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
    <% end %>
  <% end %>

  </div>
</div>

<!-- attempt to configure date-woodywood-picker -->

app/views/menus/mymenus.html.erb
<div class="container">
<div class="row">


        <% @menus.each do |menu| %>
            <div class="col-sm-12 col-md-12 col-lg-3">
            <div class="menu-card">
              <% menu_photo = (menu.photo ? cl_image_path(menu.photo.path) : image_path("no_photo_menu.png")) %>
              <div class="photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= menu_photo %>');"><%= link_to " ", menu, class: 'link-menu' %>
              </div>

              <div class="description">
                <h3><%= menu.name %></h3>
                <p><%= truncate(menu.description, :length => 40) %></p>
                <span><%= menu.price %>€</span>
              </div>

              <div class="params">
                <div class="param"><i class="fa fa-calendar"></i> <%= menu.friendly_date %></div>
                <div class="param" style="color:red; font-size: 12px; font-weight: bold"><i class="fa fa-shopping-cart" ></i> <%= menu.ordered_quantity %></div>
              </div>
                <div class="param forms" style="font-size:40px"><i class="fa fa-cutlery"></i>

                <%= simple_form_for menu do |f| %>
                  <%= f.error_notification %>
                  <%= f.input :portions, label: false, class: "form-control" %>
                <% end %>

                </div>

          </div>


  </div>
   <% end %>

   <%= link_to "Create a new menu", new_menu_path, class:'btn cta-btn' %>

</div>

</div>

app/views/menus/new.html.erb
<div class="container">
<%= render 'form', menu: @menu %>
</div>

app/views/menus/show.html.erb
<div class="show">

  <div class="container">
    <!--  left side -->
      <div class="col-xs-12 col-sm-8">
        <div class="menu-card">

          <div class="photo large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%=cl_image_path @menu.photo.path, width: 1000, height: 500, crop: :fill  %>');">
          </div>

          <%= link_to landingchef_path(@menu.user.id), class: 'link-chef-large' do %><%= @menu.user.photo ? cl_image_tag(@menu.user.photo.path, width: 300, height: 200, crop: :crop, class: 'avatar') : image_tag("no_photo.png", width: 300, height: 200, crop: :crop, class: 'avatar') %><% end %>

            <div class="params description">
              <div class="param">
                <h2><%= @menu.name %></h2>
                <div><%= @menu.description %></div>
              </div>
              <div class="param">
                <div class="price"><%= @menu.price %>€</div>
              </div>
            </div>

          <div class="params">
            <div class="param"><i class="fa fa-calendar"></i> <%= @menu.friendly_date %></div>
            <div class="param"><i class="fa fa-cutlery"></i> <%= @menu.portions %></div>
          </div>
          <div class="localisation">
            <p><i class="fa fa-map-marker"></i> <%= @menu.user.city if @menu.user.city != NIL %></p>
          </div>


        </div>
        <div class="menu-card">
          <div class="description">
            <ul>
              <li>Starter: <%= @menu.starter %></li>
              <li class="bordered">Meal: <%= @menu.meal %></li>
              <li class="bordered">Dessert: <%= @menu.dessert %></li>
            </ul>
          </div>
        </div>
      </div>

    <!--  right side -->
      <div class="right-card-container col-sm-4">

        <%= render '/orders/form', order: @order %>

        <%= render 'shared/sharing' %>

      </div>
    </div>
  </div>