config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :menus do
    resources :orders, only: [:index, :create, :update, :new]
  end
  resources :orders, only: [:destroy]

  get "chef/orders" => "orders#chef_index"

  get "orders" => "orders#index"
  get "chef/" => "pages#chef"

  get "landingchef/:id" => "pages#landingchef", as: "landingchef"
  get "orders/:id/approve" => "orders#approve", as: "approve"
  get "orders/:id/reject" => "orders#reject", as: "reject"
  get "mymenus" => "menus#mymenus"


  mount Attachinary::Engine => "/attachinary"

  resources :users, only: [:show, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">

  <a href="/">
    <h4>Beauty Food</h4>
  </a>

  <h5>Some beautyfood in your Inbox?</h5>
  <p>Receive all news about our chefs and their latest beautyfood menus</p>

<div id="mc_embed_signup">
  <form action="//lewagon.us14.list-manage.com/subscribe/post?u=8cdcf06f762ff00b3c38a7fa0&amp;id=04ec8deaa1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

    <div class="newsletter-input" id="mc_embed_signup_scroll">
    <span class="mc-field-group">
      <input type="email" value="" placeholder="you@gmail.com" name="EMAIL" class="form-control required email" id="mce-EMAIL">
    </span>
    <span id="mce-responses" class="clear">
      <div class="response" id="mce-error-response" style="display:none"></div>
      <div class="response" id="mce-success-response" style="display:none"></div>
    </span>

    <span class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary"></span>
    </div>
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8cdcf06f762ff00b3c38a7fa0_04ec8deaa1" tabindex="-1" value=""></div>
  </form>
</div>


  <ul class="list-inline footer-menu">
  <li><a href="/">HOME</a></li>
  <li><a href="#">BECOME A CHEF</a></li>
  <li><a href="#">HYGIENE</a></li>
  <li><a href="#">FAQ</a></li>
  <li><a href="#">LEGAL NOTICE</a></li>
  <li><a href="#">JOBS</a></li>
  <li><a href="#">PRESS</a></li>
  </ul>

  <p>—</p>

  <p>Copyright © BeautyFood 2016. Made with <i class="fa fa-heart"></i> in Le Wagon </p>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <h4>Beauty Food</h4>
  </a>

  <!-- Search form -->
  <%= form_tag(menus_path, method: "get", class: "navbar-wagon-search hidden-xs") do %>
    <button type="submit" class="navbar-wagon-search-btn">
      <i class="fa fa-search"></i>
    </button>
  <%= text_field_tag :city, params[:city], placeholder: 'Where?', class: 'navbar-wagon-search-input' %>
  </form>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">
    <% if !user_signed_in? || !current_user.is_chef? %>
      <%= link_to chef_path, class: "navbar-wagon-item btn navbar-wagon-button" do %> Become a chef <i class="fa fa-info"></i>
      <% end %>
    <% end %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to orders_path, class: "navbar-item navbar-wagon-link" do %>
      Orders
<!--         <div class="badge-container">
          <div class="badge badge-red">3</div>
          Orders
          <i class="fa fa-life-ring"></i>
        </div> -->
      <% end %>

    <div class="navbar-wagon-item">
        <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || current_user.photo ? cl_image_path(current_user.photo.path) : image_path("no_photo.png")%>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if user_signed_in? && current_user.is_chef? %>
            <li>
              <%= link_to chef_orders_path do %>
                <i class="fa fa-cutlery"></i>  <%= t(".profile", default: "Requests for order") %>
              <% end %>
            </li>
            <li>
              <%= link_to mymenus_path do %>
                <i class="fa fa-list"></i>  <%= t(".profile", default: "My menus") %>
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Help <i class="fa fa-life-ring"></i> </a>

    <!-- Signup text link -->
    <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg hidden-sm">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= form_tag(menus_path, method: "get", class: "searchbar") do %>
          <%= text_field_tag :city, nil, placeholder: 'City', class: 'search-city' %>
          <%= text_field_tag :date, nil, placeholder: 'Date', "data-provide" => "datepicker" %>
      <div class="styled-select">
      <%= select_tag :portions, options_for_select((1..10), :selected => params[:portions]), include_blank: 'Portions' %>
      </div>
          <%= submit_tag "Search", class: "search-btn" %>
        <% end %>
      </div>
    </div>

app/views/shared/_sharing.html.erb
<div class="text-center col-xs-12 col-sm-12 right-cards card-share menu-card">
<div><strong>Share it with your friends</strong></div>
<ul class="list-inline">
    <li>
      <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url  %>">
       <i class="fa fa-facebook"></i> Facebook
      </a>
    </li>
    <li>
      <a href="https://twitter.com/home?status=<%= request.original_url  %>">
        <i class="fa fa-twitter"></i> Twitter
      </a>
    </li>
    <li>
      <a href="https://www.linkedin.com/shareArticle?mini=true&url=<%= request.original_url  %>&title=Beautyfood&summary=&source=">
        <i class="fa fa-instagram"></i> Instagram
      </a>
    </li>
</ul>
</div>