config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :menus do
    resources :orders, only: [:index, :create, :update, :new]
  end
  resources :orders, only: [:destroy]

  get "chef/orders" => "orders#chef_index"

  get "orders" => "orders#index"
  get "chef/" => "pages#chef"

  get "landingchef/:id" => "pages#landingchef", as: "landingchef"
  get "orders/:id/approve" => "orders#approve", as: "approve"
  get "orders/:id/reject" => "orders#reject", as: "reject"
  get "mymenus" => "menus#mymenus"


  mount Attachinary::Engine => "/attachinary"

  resources :users, only: [:show, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
require 'date'
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :portions, numericality: { only_integer: true, greater_than: 0 }

  before_save :check_stock

  def buddy_date
    self.date.strftime("%e %B, %Y")
  end

  def friendly_date
    self.created_at.strftime("%e %B, %Y")
  end

  private

  def check_stock
    left = self.menu.portions - self.menu.ordered_quantity(self)
    if (self.portions) > left
      errors[:portions] <<  "You can not order more than #{left} portion#{left>1 ? 's' : ''}"
      throw :abort
    end

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :set_menu, only: [:new, :create]
before_action :set_order, only: [:destroy, :approve, :reject]

  def index
    @orders = Order.where(user_id: current_user.id).order(created_at: :desc)
  end

  def chef_index
    # @orders = current_user.menus.orders.sort { |x,y| y.created_at <=> x.created_at }
    #@orders = Order.joins("INNER JOIN menus ON orders.menu_id = menus.id AND menus.user_id = #{current_user.id}")
    @orders = Order.joins(:menu).where("menus.user_id = ?", current_user.id)
  end

  def approve
    redirect_to(chef_orders_path, alert: 'This order is not yours, fellow !') unless @order.menu.user_id == current_user.id
    if @order.update(approved:true)
      redirect_to chef_orders_path, notice: "Order approved ! It's time to shop your ingredients ..."
    else
      redirect_to chef_index_path, notice: "Sorry, this order is not to approvable"
    end
  end

  def reject
    redirect_to(chef_orders_path, alert: 'This order is not yours, fellow !') unless @order.menu.user_id == current_user.id
    if @order.update(approved:false)
      redirect_to chef_orders_path, notice: "Order rejected ! Are you really a Chef dude ?"
    else
      redirect_to chef_index_path, notice: "Sorry, this order is not rejectable"
    end
  end

  def new
    set_menu
    @order = Order.new
    @order.menu = @menu
  end

  def create
    @order = Order.new(orders_params)
    @order.menu = @menu
    @order.user = current_user
    @order.date = @menu.availability
    if @order.save
      redirect_to orders_path, notice: 'Your order is submitted for approval'
    else
      render "menus/show"
    end
  end

  def destroy
    message = 'This order is not yours, fellow !'
    if @order.user_id == current_user.id
      @order.destroy
      message = 'Your order has been successfully deleted'
    end
    redirect_to orders_path, notice: message
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_menu
      @menu = Menu.find(params[:menu_id])
  end

  def set_order
      @order = Order.find(params[:id])
  end

  def orders_params
      params.require(:order).permit(:portions)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="col-xs-12 col-sm-12 right-cards menu-card" >
  <%= simple_form_for [@menu, @order] do |f| %>
    <%= f.error_notification %>

    <% if (@menu.portions - @menu.ordered_quantity) != 0 %>

      <div class="text-center action-card col-md-12 col-sm-12 portions">
        <p><i class="fa fa-cutlery"></i>
        <% if (@menu.portions - @menu.ordered_quantity) == 1 %>
        <span class="empty"> One last portion available, hurry up!</span>
        <% else %>
        <span> Only <%= @menu.portions - @menu.ordered_quantity %> portions available!</span>
        <% end %>
        </p>
      </div>

    <div class="action-card col-md-6 col-sm-6">
      <span>Take away hours</span>
      <% hours = ["6:30pm-7:30pm", "7:30pm-8:30pm", "8:30pm-9:30pm", "9:30pm-10:30pm" ] %>
      <%= select_tag :take_away_hours, options_for_select(hours), class: "styled-select style_form " %>
    </div>

    <div class="action-card col-md-6 col-sm-6">
      <span>Pig out option</span>
      <% complement = ["0g", "+50g", "+100g", "+150g", "+200g", "+250g", "+300g", "+350g", "+400g", "+450g", "+500g"  ] %>
      <%= select_tag :pig_out_options, options_for_select(complement), class: "styled-select style_form" %>
    </div>

    <div class="action-card col-md-12 col-sm-12">
    <span>How many portions do you want?</span>
    <% portions = (1..(@menu.portions - @menu.ordered_quantity)) %>
      <%= f.input :portions, collection: portions, selected: 1, class: "", label: false %>
    </div>

    <div class="form-actions col-md-12 col-sm-12">
      <%= f.button :submit, 'A table!', class: 'btn cta-btn col-xs-12 button_style' %>
    </div>

    <% else %>
    <div class="text-center action-card col-md-12 col-sm-12 gone">
      It's all gone already. <i class="fa fa-frown-o" aria-hidden="true"></i> <br>
    </div>

    <% end %>


  <% end %>
</div>

app/views/orders/chef_index.html.erb
<div class="container">
  <div class="row">
    <div class="forms col-xs-12 col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1">
      <div class="section">
        <h2 class="text-center small">Orders</h2>
      </div>
        <% if @orders.count.zero?  %>
        <div class="orders-empty">
        <h4>You have no orders yet <i class="fa fa-frown-o" aria-hidden="true"></i></h4>
        <p>Let's go ahead to find awesome menus:</p>
        </div>
        <%= render 'shared/searchbar' %>
        <% end %>

      <% @orders.each do |order| %>

      <div class="orders">
        <div class='orders-id'>
          <div class='date'>#<%= order.id %></div>
        </div>
        <div class='orders-date space'>
          <div class='date'> <i class="fa fa-calendar" aria-hidden="true"></i> <span><%= order.friendly_date %></span></div>
        </div>
        <%
        length = order.portions
        str = "<span>#{length} </span>" + '<i class="fa fa-cutlery"></i>'
        %>
        <%= order.user.photo ? cl_image_tag(order.user.photo.path, width: 100, height: 100, crop: :fill, class: 'avatar hidden-xs space') : image_tag("no_photo.png", width: 100, height: 100, crop: :fill, class: 'avatar') %>
        <div class='orders-body space'>
          <h4 class="orders-client"><%= order.user.full_name %></h4>
          <p><%= str.html_safe %> - "<%= order.menu.name %>"</p>
        </div>
        <ul class="list-inline orders-controls hidden-sm hidden-xs space chefs">
        <% status = (order.approved.nil? ? 'pending' : (order.approved ? 'approved' : 'rejected' ) ) %>
         <% if status != 'pending' %>
        <li><p>Status: <%= status %></p></li>
        <% else %>
        <li><%= link_to approve_path(order) do %> <i class="fa fa-check order_approved"></i><% end %> | <%= link_to reject_path(order), class: "toto", title: 'reject', 'data-toggle': 'tooltip' do %> <i class="fa fa-ban order_pending"></i><% end %>
        </li>
        <% end %>
        </ul>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="forms col-xs-12 col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1">
      <div class="section">
        <h2 class="text-center small">My orders</h2>
      </div>
        <% if @orders.count.zero?  %>
        <div class="orders-empty">
        <h4>You have no orders yet <i class="fa fa-frown-o" aria-hidden="true"></i></h4>
        <p>Let's go ahead to find awesome menus:</p>
        </div>
        <%= render 'shared/searchbar' %>
        <% end %>

      <% @orders.each do |order| %>

      <div class="orders">
        <div class='orders-date'>
          <div class='date'> <i class="fa fa-calendar" aria-hidden="true"></i><br><span><%= order.buddy_date %></span></div>
        </div>
        <%= link_to menu_path(order.menu) do %>
        <%
        str = ""
        length = order.portions
        if length < 5
        (1..length).each {|i| str += '<i class="fa fa-cutlery"></i>'}
        else
          str += "<span>#{length}</span>" + '<i class="fa fa-cutlery"></i>'
        end
        %>
        <div class="orders-portions"><%= str.html_safe %></div>
        <%=
        cl_image_tag(order.menu.photo.path, width: 175, height: 130, crop: :fill, class: 'orders-image hidden-xs') %>
        <% end %>
        <div class='orders-body'>
          <h3><%= order.menu.name %></h3>
          <p>from <%= link_to order.menu.user.full_name, landingchef_path(order.menu.user) %></p>
        </div>
        <ul class="list-inline orders-controls hidden-sm hidden-xs">
<!--             <li><a href=""><i class="fa fa-heart"></i></a></li>
          <li><a href=""><i class="fa fa-share"></i></a></li>
          <li><a href=""><i class="fa fa-star"></i></a></li> -->
          <li>

          <% if order.approved.nil? %>
            <span class="order_pending"><i class="fa fa-clock-o" aria-hidden="true"></i> order is pending</span>
          <% elsif order.approved %>
            <span class="order_approved"><i class="fa fa-check-circle" aria-hidden="true"></i> order confirmed</span>
            <% else %>
             <span class="order_rejected"><i class="fa fa-ban" aria-hidden="true"></i> order rejected</span>
          <% end %>
          </li>
          <li><% if order.approved.nil? || !order.approved %>
              <%= link_to order_path(order), method: :delete do %> <i class="fa fa-trash"></i> <% end %>
            <% end %>
          </li>
        </ul>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/orders/new.html.erb
<h1>New Order on <%= @menu.name %></h1>
<% if @order %>
<%= render 'form', order: @order %>
<% else %>
<%= @message %>
<% end %>